### ISSUE TITLE
accept ROA in state WAITING FOR INVITATION ("invite")

### ISSUE THREAD

**Issue by jack-kerouac** [jack-kerouac/RoomR#46]
method on ResidentFacade

preconditions:
- RO is in state PUBLIC
- ROA is in state WAITING FOR INVITATION

actions:
- send mail to seeker with the accepted ROA
  - state that he should make an appointment (?)

post conditions:
- ROA is in state INVITED

Write test for the pre- and postconditions as well as for the actions.

see https://docs.google.com/drawings/d/1V5rpsgNq0lkfucdDsvnjUf3nhhQ9u1qmP_UXgJliAq4/edit?pli=1

**Comment by gernd** [comment]
-TODO: fix test for valid parameters (use mockito spy)

**Comment by gernd** [comment]
done
