### ISSUE TITLE
accept ROA in state INVITED

### ISSUE THREAD

**Issue by jack-kerouac** [jack-kerouac/RoomR#47]
method on ResidentFacade

right now we don't track if a seeker actually has visited the flatshare, therefore we virtually skip the state VISITED and allow all transition from VISITED also for the state INVITED.

preconditions:
- RO is in state PUBLIC
- ROA is in state INVITED or VISITED
- there is no ROA in state OFFERED or ACCEPTED for this RO

actions:
- send mail to seeker with the accepted ROA
  - include request that he should accept the offer (and thus finish the workflow) or reject the offer

post conditions:
- ROA is in state OFFERED

Write test for the pre- and postconditions as well as for the actions.

**Comment by tthraine** [comment]
not necessary in new workflow
