### ISSUE TITLE
confirm ROA in state OFFERED

### ISSUE THREAD

**Issue by jack-kerouac** [jack-kerouac/RoomR#49]
method on SeekerFacade

preconditions:
- RO is in state PUBLIC
- ROA is in state OFFERED

actions:
- send mail to residents of the RO
  - include request that they can (and should) successfully close the RO now

post conditions:
- ROA is in state ACCEPTED

Write test for the pre- and postconditions as well as for the actions.

**Comment by tthraine** [comment]
not necessary in new workflow
