### ISSUE TITLE
configure JavaScript minifying

### ISSUE THREAD

**Issue by jack-kerouac** [jack-kerouac/RoomR#5]
only on Prod mode

**Comment by tthraine** [comment]
The minifyers for Play (Press and GreenScript) _always_ output <script>-tags. This does not work with Modernizr, so we can't quite use minifying (except we stop using Modernizr for script loading).
On the bright side, we don't really have to minify our JavaScript code as long as we don't split it into multiple files, as GAE gzips all requests per default.
