### ISSUE TITLE
delete ROA (seeker has no interest anymore)

### ISSUE THREAD

**Issue by tthraine** [jack-kerouac/RoomR#50]
method on SeekerFacade

preconditions:
- RO is in state PUBLIC
- ROA is in any state other than ACCEPTED

actions:
- if ROA state is INVITED, send message to resident stating that the seeker is no longer interested

post conditions:
- ROA is deleted

Write test for the pre- and postconditions as well as for the actions.

see https://docs.google.com/drawings/d/1V5rpsgNq0lkfucdDsvnjUf3nhhQ9u1qmP_UXgJliAq4/edit?pli=1

**Comment by gernd** [comment]
TODO : add button/link to GUI to trigger deletion
